## Description

__- The idea is to design Neural Network from scratch using simple python code.__

__Note: This code doesn't contain any libraries like Tensorflow, Keras or PyTorch__

## Importing necessary Python Libraries

In [3]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets
sns.set()

## Initialize weight to small random values (+ve or -ve)

In [5]:
w = np.random.randn(3)*1e-4

In [6]:
w

array([ 5.19298691e-05,  7.99671481e-05, -1.16718276e-05])

## Activation Function

In [12]:
g = lambda ip, wt: np.where(np.dot(ip, wt)>0, 1, 0)

## Training

In [16]:
def train(inputs, targets, weights, eta, n_iter):
    # Appending biases to inputs
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]
    for n in range(n_iter):
        # Calling activation function with modifed weights(getting output
        activations = g(inputs, weights)
        print(activations)
        # Updating weights using eta * DOT(inputs, LOSS)
        weights = weights - (eta*np.dot(np.transpose(inputs), activations-targets))
        print(weights)
    # Returning weights
    return(weights)

## Learning AND gate

In [20]:
AND = pd.DataFrame({'x1':(0,0,1,1), 'x2':(0,1,0,1), 'y':(0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [21]:
inputs=AND[['x1','x2']]
target=AND['y']
w=train(inputs, target, w, 0.25, 10)

[0 1 1 1]
[0.25005193 0.25007997 0.74998833]
[0 0 0 0]
[0.50005193 0.50007997 0.49998833]
[0 1 1 1]
[0.25005193 0.25007997 0.99998833]
[0 0 0 0]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]
[0 0 0 1]
[0.50005193 0.50007997 0.74998833]


## Prediction

In [26]:
# 0 AND 1 = 0

g([0,1,-1],[0.50005193, 0.50007997, 0.74998833])

array(0)

_______________________________________________________________________

## Learning OR gate

In [22]:
OR = pd.DataFrame({'x1':(0,0,1,1), 'x2':(0,1,0,1), 'y':(0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [23]:
inputs=OR[['x1','x2']]
target=OR['y']
w=train(inputs, target, w, 0.25, 10)

[0 0 0 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]
[0 1 1 1]
[0.75005193 0.75007997 0.24998833]


## Prediction

In [25]:
# 0 OR 1 = 1


g([0,1,-1], [0.75005193, 0.75007997, 0.24998833])

array(1)